GET http://localhost:8000/business/admin/daily-train-ticket/query-list?page=1&size=5&trainCode=G10086&start=惠州&end=汕尾
Content-Type: application/json

###
GET http://localhost:8000/business/admin/daily-train-ticket/query-list2?page=1&size=5&trainCode=G10086&start=惠州&end=汕尾
Content-Type: application/json

###
GET http://localhost:8000/business/admin/daily-train-ticket/query-list3?page=1&size=5&trainCode=G10086&start=惠州&end=汕尾
Content-Type: application/json

###
