#测试乘车人保存的接口
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "test3",
  "idCard": "123321",
  "type": "1"
}
###

# 测试乘车人分页的接口
GET http://localhost:8000/member/passenger/query-list?page=1&size=3l
Accept: application/json
token: {{token}}

###

# 测试乘车人删除的接口
DELETE http://localhost:8000/member/passenger/delete/1647909834340831232
Accept: application/json
token: {{token}}

###

# 测试乘车人编辑的接口
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": "1649445442938867712",
  "memberId": "1645987570351476736",
  "name": "update_test",
  "idCard": "123321",
  "type": "1"
}
###