#测试获取总数的接口
GET http://localhost:8000/member/member/count
Accept: application/json

###

#测试注册接口
POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=12345864785

###

#测试发送验证码的接口
POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
  "mobile":"13543183846"
}
###


#测试登录的接口
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "13543183846",
  "code": "8888"
}

> {%
client.log(JSON.stringify(response.body));
client.log(JSON.stringify(response.body.content.token));
client.global.set("token", response.body.content.token);
%}
###
